#!/bin/bash

#(CHECKSIZE) Да се състави командна процедура, която получава в командния ред при стартиране два параметъра – първият от които – символен низ, а вторият – число. Ако съществува директория с име, съвпадащо с низа, процедурата извежда на стандартния изход имената на всички обикновени файлове в нея, които имат размер (в символи) по-голям от подаденото число. В противен случай (ако не съществува такава директория) – на стандартния изход се извежда подходящо съобщение.

declare directory
declare number

read directory number

if test -d $directroy
then
	for name in $directory/*
	do
		if test -f $name -a `wc -c <$name` -gt $number
		then echo $name
		fi
	done
else
	echo There is no such dircetory
fi
